name: generate-notes

on:
  workflow_dispatch:
    inputs:
      installerChartRegistry:
        description: 'Installer Chart Registry'
        type: string
        required: true
        default: 'https://charts.krateo.io/'
      installerChartRepository:
        description: 'Installer Chart Reporitory'
        type: string
        required: true
        default: 'installer'
      installerChartGithubRepository:
        description: 'Installer Chart Github Reporitory'
        type: string
        required: true
        default: 'installer-chart'
      installerChartVersion:
        description: 'Installer Chart Version'
        type: string
        required: true
        default: '2.5.0'
      installerChartVersionPrevious:
        description: 'Installer Chart Previous Version'
        type: string
        required: true
        default: '2.4.3'
      organization:
        description: 'GitHub Organization to retrieve release notes from'
        type: string
        required: true
        default: 'krateoplatformops'

env:
  GHCR_REPO: ghcr.io/${{ github.repository }}

jobs:
  generate-notes:
    permissions:
      contents: read
      pull-requests: read
      issues: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - run: |
          go run main.go
        env:
          INSTALLER_CHART_REGISTRY: ${{ inputs.installerChartRegistry }}
          INSTALLER_CHART_REPOSITORY: ${{ inputs.installerChartRepository }}
          INSTALLER_CHART_GITHUB_REPOSITORY: ${{ inputs.installerChartGithubRepository }}
          INSTALLER_CHART_VERSION: ${{ inputs.installerChartVersion }}
          INSTALLER_CHART_VERSION_PREVIOUS: ${{ inputs.installerChartVersionPrevious }}
          TOKEN: ${{ secrets.TOKEN_CONTENTS_WORKFLOWS }}
          ORGANIZATION: ${{ inputs.organization }}
      - id: "RELEASE_NOTES"
        run: cat release_notes.md
